name: Build app Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 for Spring Boot app
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Spring Boot app with Maven
      run: mvn --file ./api/pom.xml --batch-mode --update-snapshots package
    - name: Sign in to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Spring Boot app Docker image
      run: docker build ./api --file ./api/Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_SPRING}}:$(date +%s)
    - name: List Docker images
      run: docker images
    - name: Push Spring Boot app image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_SPRING}}

    - name: Set up Node.js for React client
      uses: actions/setup-node@v3
      with:
        node-version: '18.2.0'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm install
      working-directory: frontend
    - run: npm run build
      working-directory: frontend
      env:
        CI: false
    - run: npm test
      working-directory: frontend
    - name: Build React client Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_REACT}}:$(date +%s)
    - name: Push React app image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_REACT}}