name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --file ./api/pom.xml --batch-mode --update-snapshots package
    - name: Build the Docker image
      run: docker build ./api --file ./api/Dockerfile --tag notes-eks-api:$(date +%s)